// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzzmvyypguyzmotccvfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6em12eXlwZ3V5em1vdGNjdmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjU1MjcsImV4cCI6MjA2NjI0MTUyN30.HOpsfc1Mq3XTWi190EkvVIKxaP79NwY9163CLNcNXhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);